---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-secret
  labels:
    app: cityapp-secret
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: cityapp-secret
  type: LoadBalancer

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cityapp-secret
  name: cityapp-secret
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: cityapp-secret
  wildcardPolicy: None

---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: cityapp-secret
  name: cityapp-secret
spec:
  replicas: 1
  selector:
    app: cityapp-secret
  template:
    metadata:
      labels:
        app: cityapp-secret
    spec:
      serviceAccountName: cityapp-secret
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/cityapp/cityapp:springboot-0.1
        imagePullPolicy: Always
        name: cityapp
        env:
          - name: DBUrl
            value: jdbc:oracle:thin:@10.0.0.20:1521:xe
          - name: DBUsername
            valueFrom:
              secretKeyRef:
                name: cityapp-secret
                key: spring.datasource.username
          - name: DBPassword
            valueFrom:
              secretKeyRef:
                name: cityapp-secret
                key: spring.datasource.password
        ports:
        - containerPort: 8080
          name: http

