---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: cityapp-secret
data:
  spring.datasource.password: TmV3UGFzc3dvcmQK
  spring.datasource.username: Y2l0eWFwcA==
  spring.datasource.url: amRiYzpvcmFjbGU6dGhpbjpAMTAuMC4wLjIwOjE1MjE6eGUK

